name: Pull request pipeline

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# for security reasons the github actions are pinned to specific release versions
jobs:
  link_checker:
    name: Link checker
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.7.0
        with:
          args: >-
            --exclude 'github\.com/OWASP/DevGuide/blob/main/docs'
            --no-progress
            --max-retries 1
            --retry-wait-time 10
            --max-concurrency 2
            'docs/**/*.md'
            'docs/*.md'
            '*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  md_linter:
    name: Lint markdown
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v22.0.0
        with:
          config: '.markdownlint.yaml'
          globs: |
            docs/**/*.md
            docs/*.md
            *.md

  spell_checker_en:
    name: Check EN spelling
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Spell check EN language
        uses: rojopolis/spellcheck-github-actions@0.55.0
        with:
          config_path: .spellcheck-en.yaml

  spell_checker_es:
    name: Check ES spelling
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Spell check ES language
        uses: rojopolis/spellcheck-github-actions@0.55.0
        with:
          config_path: .spellcheck-es.yaml

  spell_checker_pt-br:
    name: Check PT-BR spelling
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      # rojopolis/spellcheck-github-actions does not support PT-BR,
      # only PT, and PT-BR is too different to pass a PT spellcheck
      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: '3.10'

      - name: Install pyspelling
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pyspelling
          sudo apt-get install aspell aspell-pt

      - name: Spell check PT-BR release
        run: |
          python -m pyspelling --config .spellcheck-pt-br.yaml

  build_check:
    name: Build check
    runs-on: ubuntu-24.04
    needs: [md_linter, spell_checker_en, spell_checker_es, spell_checker_pt-br]
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Install python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.x

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mkdocs
          pip install mkdocs-material 
          pip install mkdocs-open-in-new-tab
          pip install mkdocs-redirects
          pip install mkdocs-with-pdf

      - name: Copy contributing tab files
        run: |
          cp code_of_conduct.md docs/.
          cp contributing.md docs/.
          cp license.txt docs/.

      - name: Build docs
        run: mkdocs build

  export_pdf:
    name: Export PDFs
    runs-on: ubuntu-24.04
    needs: [build_check]
    steps:
      - name: Checkout markdown
        uses: actions/checkout@v6.0.1

      - name: Install python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.x

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install mkdocs
          pip install mkdocs-material 
          pip install mkdocs-open-in-new-tab
          pip install mkdocs-redirects
          pip install mkdocs-with-pdf

      - name: Build pdf for EN
        run: mkdocs build --config-file mkdocs-pdf-en.yaml

      - name: Build pdf for ES
        run: mkdocs build --config-file mkdocs-pdf-es.yaml

      - name: Build pdf for FA
        run: mkdocs build --config-file mkdocs-pdf-fa.yaml

      - name: Build pdf for PT-BR
        run: mkdocs build --config-file mkdocs-pdf-pt-br.yaml
